### ISSUE TITLE
When the generator starts, no documentation is generated

### ISSUE THREAD

**Issue by Darkildo** [BreX900/open_api#2]
Even if I try to follow the guide from the repository using the example in it, nothing works. If I delete the example.openapi.yaml file, the system does not generate it again :(
Dart SDK version: 3.1.0 (stable) on "windows_x64"

I tried downgrading dart version but it didn't help:

fvm dart --version                                                    
Dart SDK version: 2.19.6 (stable)  on "windows_x64"

**Comment by BreX900** [comment]
Sorry for the problem
I have released a new version `1.1.0` of `shelf_open_api` and `shelf_open_api_generator` fixing the problem.
I have also updated the minimum version of dart to `3.0.0` and supported the latest version of the analyzer
Now everything should work correctly

Could you try?

**Comment by Darkildo** [comment]
Thanks, now all work fine, its really cool.
